version: "2.1"
   
services:
  db:
      image: mysql:5.7
      container_name: mysqldb
      restart: always
      ports :
        - target : 3306
          published : 3306
          protocol: tcp
      environment:
        MYSQL_ROOT_PASSWORD: 'root'
        MYSQL_DATABASE: 'test'
        MYSQL_USER: 'student'
        MYSQL_PASSWORD: 'abc123'
      command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
      healthcheck:
        test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
        interval: 3s
        timeout: 1s
        retries: 5
      
  web:
    build : .
    ports:
      - "8000:8000"
    depends_on:
       db :
        condition: service_healthy
    restart : always
    links :
       - db
    stdin_open : true
    tty : true